server:
  port: 8080

spring:
  application:
    name: spring_security_jwt

  datasource:
    url: jdbc:h2:~/${DATABASE_NAME:security};MODE=MySQL
    # jdbc:h2:tcp://localhost/~/lee-do
    username: sa
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    expire-time: ${JWT_ACCESS_TOKEN_EXPIRES:3600000}
  refresh:
    expire-time: ${JWT_REFRESH_TOKEN_EXPIRES:86400000}
